### PR TITLE
switch out most graphics for an svg simplified equivalent

### PR DESCRIPTION
**Pull request by idrysdale**
Using SVGs means the graphics scale lossly.

I didn't make one for 04, the screenshot of the checkboxes on github's
branch protection options, rather just removed the travis item.

### CODE REVIEW

**Comment by idrysdale** [comment]
Ah, good spot, I'll convert to outlines and reupload!

**Comment by paulfurley** [comment]
Checking now!

**Comment by paulfurley** [comment]
Bottom one looks great, top one the same! 

image

**Comment by paulfurley** [comment]
Nope :(

**Pull request merged**
